import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";

const almarai = Almarai({
  weight: ["400", "800", "300", "700"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "الدليل الرقمي",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={almarai.className}>{children}</body>
    </html>
  );
}
